backend:
  name: github
  repo: tarpey/bcc-gatsby

local_backend: false

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    folder: "src/content/pages"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Type", name: "type", widget: "hidden", default: "audience" }
      - {
          label: "Audience",
          name: "audience",
          widget: "select",
          options:
            [
              { label: "Residents", value: "residents" },
              { label: "Business", value: "business" },
              { label: "Council and Mayor", value: "council-and-mayor" },
            ],
        }
      - { label: "Path", name: "path", widget: "string" }
      - {
          label: "Parent",
          name: "parent",
          widget: "relation",
          collection: "pages",
          searchFields: ["title"],
          valueField: "{{path}}",
          displayFields: "title",
          required: false,
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }
