backend:
  name: github
  repo: tarpey/bcc-gatsby

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    folder: "src/content/articles"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Content", name: "content", widget: "markdown" }
      - {
          label: "Type",
          name: "type",
          widget: "select",
          options:
            [
              { label: "Category", value: "category" },
              { label: "Article", value: "article" },
            ],
          default: "article",
        }
